### ISSUE TITLE
Precisa de mais Assembly

### ISSUE THREAD

**Issue by fabiodrg** [xRuiAlves/AEDA-2017-18#1]
Muito pouco eficiente

**Comment by miguelpduarte** [comment]
Agreed!

**Comment by miguelpduarte** [comment]
- [ ] Tentar configurar masm no Visual Studio
- [x] Falhar redondamente
- [x] Chorar
- [x] Conseguir (lol nunca)
- [ ] SEGFAULT party!
- [ ] Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
- [x] Obligatory lorem ipsum
- [ ] Reparar que afinal esta é a cadeira errada
- [x] Chumbar
- [x] História da arte, campo alegre
- [ ] Adjuntar corretamente
- [x] Bonus step
- [x] Para o ano há mais
